name: setup-env
description: "Setup environment"

inputs:
  python-version:
    default: "3.11"
    description: Python version to use
  upgrade:
    default: "false"
    description: If 'true', upgrades all packages before creating the env

runs:
  using: composite

  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}

    - shell: bash
      if: ${{ inputs.upgrade == 'true' }}
      run: uv lock --upgrade

    - shell: bash
      run: uv sync --link-mode copy --locked
