name: test

on:
  pull_request:

jobs:
  pytest:
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        os: ["ubuntu-latest"]
        upgrade: ["false"]
        include:
          - os: windows-latest
            python-version: "3.11"
            upgrade: "false"
          - os: macos-latest
            python-version: "3.11"
            upgrade: "false"
          - os: ubuntu-latest
            python-version: "3.14"
            upgrade: "true"
      fail-fast: false

    runs-on: ${{ matrix.os }}
    name: test / pytest (${{ matrix.os }}, ${{ matrix.python-version }}${{ matrix.upgrade == 'true' && ', upgrade' || '' }})

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          python-version: ${{ matrix.python-version }}
          frozen: ${{ matrix.frozen }}

      - name: Run tests
        shell: bash
        run: |
          uv run pytest \
            --cov compyre --cov ./tests --cov-report term-missing --cov-fail-under 100
