name: test

on:
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run tests
        run: |
          uv run pytest \
            --cov compyre --cov ./tests --cov-report term-missing --cov-fail-under 100
